import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    toggleLang: 'عربي',

    appTitle: 'Face Recognition System',
    navVideoStream: 'Video Stream',
    navCheckIns: 'Check-Ins',
    navCompanies: 'Companies',
    navPersons: 'Persons',
    navCameras: 'Cameras',
    navSpectacles: 'Outings',
    navReturns: 'Returns',
    navAccess: 'Access',
    logout: 'Logout',

    loading: 'Loading...',
    errorPrefix: 'Error',
    edit: 'Edit',
    delete: 'Delete',
    create: 'Create',
    update: 'Update',
    cancel: 'Cancel',
    activate: 'Activate',
    deactivate: 'Deactivate',
    actions: 'Actions',
    connected: 'Connected',
    disconnected: 'Disconnected',
    connecting: 'Connecting...',
    statusLabel: 'Status',
    yes: 'yes',
    no: 'no',
    na: 'N/A',
    unknown: 'Unknown',

    companiesTitle: 'Companies',
    addCompany: 'Add Company',
    editCompany: 'Edit Company',
    companyName: 'Company Name',
    deleteConfirmCompany: 'Are you sure you want to delete this company?',

    personsTitle: 'Persons',
    addPerson: 'Add Person',
    editPerson: 'Edit Person',
    matricule: 'Matricule',
    lastName: 'Last Name',
    firstName: 'First Name',
    company: 'Company',
    selectCompany: 'Select Company',
    deleteConfirmPerson: 'Are you sure you want to delete this person?',

    camerasTitle: 'Cameras',
    addCamera: 'Add Camera',
    editCamera: 'Edit Camera',
    ipAddress: 'IP Address',
    modelName: 'Model Name',
    username: 'Username',
    password: 'Password',
    rtspPort: 'RTSP Port',
    streamPath: 'Stream Path',
    rtspPreviewLabel: 'RTSP URL Preview',
    checkStreams: 'Check Streams Now',
    statusOnline: 'ONLINE',
    statusOffline: 'OFFLINE',
    statusChecking: 'CHECKING...',
    streamLabel: 'Stream',
    userLabel: 'User',
    ipLabel: 'IP',
    rtspLabel: 'RTSP',
    deleteConfirmCamera: 'Are you sure you want to delete this camera?',

    spectaclesTitle: 'Outings',
    addSpectacle: 'Add Outing',
    editSpectacle: 'Edit Outing',
    filterAll: 'All',
    filterPending: 'Pending',
    filterCompleted: 'Completed',
    dateSortieLabel: 'Exit Date',
    dateLimiteLabel: 'Return Deadline',
    dateRentreeLabel: 'Return Date',
    markReturned: 'Mark Returned',
    person: 'Person',
    selectPerson: 'Select Person',
    selectOutingTitle: 'All outing titles',
    dropzoneText: 'Drag and drop an Excel file here (.xlsx, .xls)',
    chooseExcel: 'Choose Excel File',
    excelHint: 'Expected columns: matricule (or mat), date_sortie, date_limite_retour.',
    excelFormatPreviewTitle: 'Expected Excel Shape',
    excelTitleFromFileRule: 'Outing title is taken from the Excel file name (without extension).',
    excelColumnMat: 'matricule (or mat)',
    excelColumnSortie: 'date_sortie',
    excelColumnLimite: 'date_limite_retour',
    excelExampleRow: 'Example row',
    importedPrefix: 'Imported',
    importedCreated: 'created',
    importedErrors: 'errors',
    sortieLabel: 'Exit',
    limiteLabel: 'Deadline',
    rentreeLabel: 'Return',
    pendingBadge: 'Pending',
    completedBadge: 'Completed',
    deleteConfirmSpectacle: 'Are you sure you want to delete this outing record?',

    rentreesTitle: 'Returns',
    allReturns: 'All Returns',
    lateReturnsOnly: 'Late Returns Only',
    startCameraRecognition: 'Start Camera Recognition',
    stopCameraRecognition: 'Stop Camera Recognition',
    recentEvents: 'Recent Camera Return Events',
    lateLabel: 'Late',
    onTimeLabel: 'On Time',
    cameraStatus: 'Camera',
    socketError: 'Camera websocket error',
    websocketErrorOccurred: 'WebSocket error occurred',
    websocketConnectionFailed: 'Failed to create WebSocket connection',
    alreadyConnected: 'Already connected',

    checkInsTitle: 'Face Recognition - Check-Ins',
    startRecognition: 'Start Recognition',
    stopRecognition: 'Stop Recognition',
    noFacesDetected: 'No faces detected',
    unknownPerson: 'Unknown Person',
    stateLabel: 'State',
    companyLabel: 'Company',
    exitDateLabel: 'Exit Date',
    errorLabel: 'Error',
    timeLabel: 'Time',
    inSpectacle: 'IN OUTING',
    notOnSpectacle: 'NOT IN OUTING',
    noMatch: 'NO MATCH',

    videoStreamTitle: 'Face Recognition - Live Video Stream',
    connect: 'Connect',
    disconnect: 'Disconnect',
    detectionsTitle: 'Detections',
    fpsLabel: 'FPS',
    facesDetectedLabel: 'Faces Detected',
    face: 'Face',
    noFacesText: 'No faces detected',
    dataUnavailable: 'Detection data unavailable',

    homeTitle: 'Face Recognition System',
    homeWelcome: 'Welcome to the Face Recognition System. Use the navigation menu to access the available features.',
    homeVideoStream: 'Video Stream',
    homeVideoStreamDesc: 'Real-time face recognition with live WebSocket streaming.',
    homeCheckIns: 'Check-Ins',
    homeCheckInsDesc: 'Face recognition check-in system with color-coded status indicators.',
    homeCompanies: 'Companies',
    homeCompaniesDesc: 'Manage company records and organizational associations.',
    homePersons: 'Persons',
    homePersonsDesc: 'Manage person records and face recognition metadata.',
    homeCameras: 'Cameras',
    homeCamerasDesc: 'Configure and manage RTSP camera feeds.',
    homeSpectacles: 'Outings',
    homeSpectaclesDesc: 'Track outing requests, exit dates, and return deadlines.',
    homeReturns: 'Returns',
    homeReturnsDesc: 'Monitor and manage return records and late arrivals.',
    guestNotificationSocket: 'Guest Notification Socket',
    guestsOnline: 'Guests Online',
    noGuestsOnline: 'No guests online',
    guestNotifications: 'Guest Notifications',
    noGuestActivity: 'No recent guest activity',
    guestConnectedAt: 'connected at',
    guestDisconnectedAt: 'disconnected at',

    signInTitle: 'Sign In',
    signInSubtitle: 'Use your admin or guest account credentials.',
    signInButton: 'Sign In',
    signingIn: 'Signing in...',
    loginFailed: 'Login failed',
    invalidCredentials: 'Credentials invalid',
    haveRegistrationToken: 'Have a registration token?',
    createAccount: 'Create account',
    registerWithTokenTitle: 'Register With Token',
    registerWithTokenSubtitle: 'Paste the registration token provided by an administrator.',
    registrationToken: 'Registration Token',
    createAccountButton: 'Create Account',
    creatingAccount: 'Creating account...',
    alreadyRegistered: 'Already registered?',
    signInLower: 'Sign in',
    registrationFailed: 'Registration failed',
    accountCreatedAs: 'Account created as',
    canNowSignIn: 'You can now sign in.',

    accessControlTitle: 'Access Control',
    issueRegistrationToken: 'Issue Registration Token',
    label: 'Label',
    roleToGrant: 'Role To Grant',
    maxUses: 'Max Uses',
    expiresInHours: 'Expires In (Hours)',
    issueToken: 'Issue Token',
    grantTokenIssued: 'Grant token issued. Copy it now; it is shown only once.',
    registrationTokenLabel: 'Registration Token',
    roleLabel: 'Role',
    expiresLabel: 'Expires',
    grantRoleToExistingUser: 'Grant Role To Existing User',
    grantRoleButton: 'Grant Role',
    updatedUserRolePrefix: 'Updated',
    updatedUserRoleMiddle: 'to role',
    createGuestAccount: 'Create Guest Account',
    createGuestButton: 'Create Guest',
    guestAccountCreated: 'Guest account created.',
    manageGuestAccounts: 'Manage Guest Accounts',
    noGuestAccountsFound: 'No guest accounts found.',
    idLabel: 'ID',
    activeLabel: 'Active',
    lastSeenLabel: 'Last Seen',
    onlineLabel: 'online',
    offlineLabel: 'offline',
    newPasswordOptional: 'New password (optional)',
    save: 'Save',
    guestAccountUpdated: 'Guest account updated.',
    guestAccountDeleted: 'Guest account deleted.',
    failedCreateToken: 'Failed to create token',
    failedGrantRole: 'Failed to grant role',
    failedCreateGuest: 'Failed to create guest',
    failedUpdateGuest: 'Failed to update guest',
    failedDeleteGuest: 'Failed to delete guest',
  },

  ar: {
    toggleLang: 'English',

    appTitle: 'نظام التعرف على الوجه',
    navVideoStream: 'البث المباشر',
    navCheckIns: 'تسجيل الحضور',
    navCompanies: 'الشركات',
    navPersons: 'الأفراد',
    navCameras: 'الكاميرات',
    navSpectacles: 'سجلات الخروج',
    navReturns: 'سجلات العودة',
    navAccess: 'الصلاحيات',
    logout: 'تسجيل الخروج',

    loading: 'جاري التحميل...',
    errorPrefix: 'خطأ',
    edit: 'تعديل',
    delete: 'حذف',
    create: 'إنشاء',
    update: 'تحديث',
    cancel: 'إلغاء',
    activate: 'تفعيل',
    deactivate: 'إلغاء التفعيل',
    actions: 'الإجراءات',
    connected: 'متصل',
    disconnected: 'غير متصل',
    connecting: 'جار الاتصال...',
    statusLabel: 'الحالة',
    yes: 'نعم',
    no: 'لا',
    na: 'غير متوفر',
    unknown: 'غير معروف',

    companiesTitle: 'الشركات',
    addCompany: 'إضافة شركة',
    editCompany: 'تعديل شركة',
    companyName: 'اسم الشركة',
    deleteConfirmCompany: 'هل أنت متأكد من حذف هذه الشركة؟',

    personsTitle: 'الأفراد',
    addPerson: 'إضافة فرد',
    editPerson: 'تعديل فرد',
    matricule: 'المعرّف',
    lastName: 'اللقب',
    firstName: 'الاسم',
    company: 'الشركة',
    selectCompany: 'اختر الشركة',
    deleteConfirmPerson: 'هل أنت متأكد من حذف هذا الفرد؟',

    camerasTitle: 'الكاميرات',
    addCamera: 'إضافة كاميرا',
    editCamera: 'تعديل كاميرا',
    ipAddress: 'عنوان IP',
    modelName: 'اسم الطراز',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    rtspPort: 'منفذ RTSP',
    streamPath: 'مسار البث',
    rtspPreviewLabel: 'معاينة رابط RTSP',
    checkStreams: 'فحص البث الآن',
    statusOnline: 'متصل',
    statusOffline: 'غير متصل',
    statusChecking: 'جار الفحص...',
    streamLabel: 'البث',
    userLabel: 'المستخدم',
    ipLabel: 'العنوان',
    rtspLabel: 'RTSP',
    deleteConfirmCamera: 'هل أنت متأكد من حذف هذه الكاميرا؟',

    spectaclesTitle: 'سجلات الخروج',
    addSpectacle: 'إضافة سجل خروج',
    editSpectacle: 'تعديل سجل خروج',
    filterAll: 'الكل',
    filterPending: 'قيد الانتظار',
    filterCompleted: 'مكتمل',
    dateSortieLabel: 'تاريخ الخروج',
    dateLimiteLabel: 'آخر موعد للعودة',
    dateRentreeLabel: 'تاريخ العودة',
    markReturned: 'تسجيل العودة',
    person: 'الفرد',
    selectPerson: 'اختر الفرد',
    selectOutingTitle: 'كل عناوين الخروج',
    dropzoneText: 'اسحب وأفلت ملف Excel هنا (.xlsx, .xls)',
    chooseExcel: 'اختر ملف Excel',
    excelHint: 'الأعمدة المتوقعة: matricule (أو mat)، date_sortie، date_limite_retour.',
    excelFormatPreviewTitle: 'شكل ملف Excel المتوقع',
    excelTitleFromFileRule: 'عنوان الخروج يُؤخذ من اسم ملف Excel (بدون الامتداد).',
    excelColumnMat: 'matricule (أو mat)',
    excelColumnSortie: 'date_sortie',
    excelColumnLimite: 'date_limite_retour',
    excelExampleRow: 'مثال على سطر',
    importedPrefix: 'تم استيراد',
    importedCreated: 'تم الإنشاء',
    importedErrors: 'أخطاء',
    sortieLabel: 'الخروج',
    limiteLabel: 'الموعد النهائي',
    rentreeLabel: 'العودة',
    pendingBadge: 'قيد الانتظار',
    completedBadge: 'مكتمل',
    deleteConfirmSpectacle: 'هل أنت متأكد من حذف سجل الخروج هذا؟',

    rentreesTitle: 'سجلات العودة',
    allReturns: 'كل العودات',
    lateReturnsOnly: 'العودات المتأخرة فقط',
    startCameraRecognition: 'بدء التعرف بالكاميرا',
    stopCameraRecognition: 'إيقاف التعرف بالكاميرا',
    recentEvents: 'أحدث أحداث العودة عبر الكاميرا',
    lateLabel: 'متأخر',
    onTimeLabel: 'في الوقت',
    cameraStatus: 'الكاميرا',
    socketError: 'خطأ في WebSocket الكاميرا',
    websocketErrorOccurred: 'حدث خطأ في WebSocket',
    websocketConnectionFailed: 'فشل إنشاء اتصال WebSocket',
    alreadyConnected: 'متصل بالفعل',

    checkInsTitle: 'التعرف على الوجه - تسجيل الحضور',
    startRecognition: 'بدء التعرف',
    stopRecognition: 'إيقاف التعرف',
    noFacesDetected: 'لم يتم اكتشاف أي وجه',
    unknownPerson: 'شخص غير معروف',
    stateLabel: 'الحالة',
    companyLabel: 'الشركة',
    exitDateLabel: 'تاريخ الخروج',
    errorLabel: 'خطأ',
    timeLabel: 'الوقت',
    inSpectacle: 'في الخروج',
    notOnSpectacle: 'ليس في خروج',
    noMatch: 'لا يوجد تطابق',

    videoStreamTitle: 'التعرف على الوجه - بث فيديو مباشر',
    connect: 'اتصال',
    disconnect: 'قطع الاتصال',
    detectionsTitle: 'الاكتشافات',
    fpsLabel: 'إطار/ث',
    facesDetectedLabel: 'عدد الوجوه',
    face: 'وجه',
    noFacesText: 'لم يتم اكتشاف أي وجه',
    dataUnavailable: 'بيانات الاكتشاف غير متاحة',

    homeTitle: 'نظام التعرف على الوجه',
    homeWelcome: 'مرحباً بك في نظام التعرف على الوجه. استخدم قائمة التنقل للوصول إلى الميزات المتاحة.',
    homeVideoStream: 'البث المباشر',
    homeVideoStreamDesc: 'تعرف لحظي على الوجه مع بث WebSocket مباشر.',
    homeCheckIns: 'تسجيل الحضور',
    homeCheckInsDesc: 'نظام تسجيل حضور بالتعرف على الوجه مع مؤشرات حالة ملونة.',
    homeCompanies: 'الشركات',
    homeCompaniesDesc: 'إدارة سجلات الشركات والارتباطات التنظيمية.',
    homePersons: 'الأفراد',
    homePersonsDesc: 'إدارة ملفات الأفراد وبيانات التعرف على الوجه.',
    homeCameras: 'الكاميرات',
    homeCamerasDesc: 'إعداد وإدارة بث كاميرات RTSP.',
    homeSpectacles: 'سجلات الخروج',
    homeSpectaclesDesc: 'متابعة طلبات الخروج وتواريخ المغادرة ومواعيد العودة.',
    homeReturns: 'سجلات العودة',
    homeReturnsDesc: 'مراقبة وإدارة سجلات العودة والتأخير.',
    guestNotificationSocket: 'مقبس إشعارات الضيوف',
    guestsOnline: 'الضيوف المتصلون',
    noGuestsOnline: 'لا يوجد ضيوف متصلون',
    guestNotifications: 'إشعارات الضيوف',
    noGuestActivity: 'لا يوجد نشاط حديث للضيوف',
    guestConnectedAt: 'اتصل عند',
    guestDisconnectedAt: 'انقطع عند',

    signInTitle: 'تسجيل الدخول',
    signInSubtitle: 'استخدم بيانات حساب المدير أو الضيف.',
    signInButton: 'دخول',
    signingIn: 'جار تسجيل الدخول...',
    loginFailed: 'فشل تسجيل الدخول',
    invalidCredentials: 'بيانات الدخول غير صحيحة',
    haveRegistrationToken: 'هل لديك رمز تسجيل؟',
    createAccount: 'إنشاء حساب',
    registerWithTokenTitle: 'التسجيل بواسطة الرمز',
    registerWithTokenSubtitle: 'ألصق رمز التسجيل الذي يقدمه المدير.',
    registrationToken: 'رمز التسجيل',
    createAccountButton: 'إنشاء الحساب',
    creatingAccount: 'جار إنشاء الحساب...',
    alreadyRegistered: 'مسجل مسبقاً؟',
    signInLower: 'تسجيل الدخول',
    registrationFailed: 'فشل التسجيل',
    accountCreatedAs: 'تم إنشاء الحساب بدور',
    canNowSignIn: 'يمكنك الآن تسجيل الدخول.',

    accessControlTitle: 'إدارة الصلاحيات',
    issueRegistrationToken: 'إصدار رمز تسجيل',
    label: 'الوصف',
    roleToGrant: 'الدور الممنوح',
    maxUses: 'أقصى عدد استخدام',
    expiresInHours: 'ينتهي بعد (ساعات)',
    issueToken: 'إصدار الرمز',
    grantTokenIssued: 'تم إصدار رمز التسجيل. انسخه الآن لأنه يظهر مرة واحدة فقط.',
    registrationTokenLabel: 'رمز التسجيل',
    roleLabel: 'الدور',
    expiresLabel: 'ينتهي',
    grantRoleToExistingUser: 'منح دور لمستخدم موجود',
    grantRoleButton: 'منح الدور',
    updatedUserRolePrefix: 'تم تحديث',
    updatedUserRoleMiddle: 'إلى الدور',
    createGuestAccount: 'إنشاء حساب ضيف',
    createGuestButton: 'إنشاء ضيف',
    guestAccountCreated: 'تم إنشاء حساب الضيف.',
    manageGuestAccounts: 'إدارة حسابات الضيوف',
    noGuestAccountsFound: 'لا توجد حسابات ضيوف.',
    idLabel: 'المعرف',
    activeLabel: 'مفعل',
    lastSeenLabel: 'آخر ظهور',
    onlineLabel: 'متصل',
    offlineLabel: 'غير متصل',
    newPasswordOptional: 'كلمة مرور جديدة (اختياري)',
    save: 'حفظ',
    guestAccountUpdated: 'تم تحديث حساب الضيف.',
    guestAccountDeleted: 'تم حذف حساب الضيف.',
    failedCreateToken: 'فشل إنشاء الرمز',
    failedGrantRole: 'فشل منح الدور',
    failedCreateGuest: 'فشل إنشاء الضيف',
    failedUpdateGuest: 'فشل تحديث الضيف',
    failedDeleteGuest: 'فشل حذف الضيف',
  },
};

export const LangContext = createContext(null);

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState('en');
  const toggle = () => setLang((l) => (l === 'en' ? 'ar' : 'en'));
  const T = translations[lang];
  return <LangContext.Provider value={{ lang, toggle, T }}>{children}</LangContext.Provider>;
};

export const useLang = () => useContext(LangContext);
