version: "3.9"

services:
  react:
    build:
      context: ./REACT_CLIENT
    container_name: fr_react
    restart: unless-stopped
    environment:
      VITE_BACKEND_IP: ${VITE_BACKEND_IP:-192.168.1.105}
    ports:
      - "3000:3000"
